import Head from "next/head";

const AdminPage = (props) => {
  return (
    <>
      <Head>
        <title>VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Admin</h1>
    </>
  );
};

AdminPage.auth = {
  allowedRoles: ["ADMIN"],
};

export default AdminPage;
