import type { NextPage } from "next";
import Head from "next/head";

const Onboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Onboard</h1>
    </>
  );
};

export default Onboard;
