import type { NextPage } from "next";
import Head from "next/head";
import prisma from "lib/prisma";

const Meeting: NextPage = (props: any) => {
  const { meeting } = props;
  return (
    <>
      <Head>
        <title>Meeting | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{meeting.title}</h1>
    </>
  );
};

export default Meeting;

export async function getServerSideProps(context) {
  const id = Number(context.params.id);

  if (!id) {
    return {
      redirect: {
        destination: "/meetings",
        permanent: false,
      },
    };
  }

  const meeting = await prisma.meeting.findUnique({
    where: { id },
    select: {
      id: true,
      title: true,
    },
  });
  return {
    props: { meeting },
  };
}
