import type { NextPage } from "next";
import Head from "next/head";

const Meeting: NextPage = () => {
  return (
    <>
      <Head>
        <title>Meeting | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>meeting/[id]</h1>
    </>
  );
};

export default Meeting;
