import type { NextPage } from "next";
import prisma from "lib/prisma";
import Head from "next/head";

const Meetings: NextPage = (props: any) => {
  const { meetings } = props;
  return (
    <>
      <Head>
        <title>Meetings | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>meetings</h1>
      <ol>
        {meetings.map((project) => (
          <li key={project.id}>{project.title}</li>
        ))}
      </ol>
    </>
  );
};

export default Meetings;

export async function getServerSideProps(context) {
  const meetings = await prisma.meeting.findMany({
    select: {
      id: true,
      title: true,
    },
  });
  return {
    props: { meetings },
  };
}
