import type { NextPage } from "next";
import prisma from "lib/prisma";
import Head from "next/head";
import Link from "next/link";

const Meetings: NextPage = (props: any) => {
  const { meetings } = props;
  return (
    <>
      <Head>
        <title>Meetings | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>meetings</h1>
      <ol>
        {meetings.map(({ id, title }) => (
          <li key={id}>
            <Link href={`/meetings/${id}`}>{title}</Link>
          </li>
        ))}
      </ol>
    </>
  );
};

export default Meetings;

export async function getServerSideProps(context) {
  const meetings = await prisma.meeting.findMany({
    select: {
      id: true,
      title: true,
    },
  });
  return {
    props: { meetings },
  };
}
