import type { NextPage } from "next";
import Head from "next/head";

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Projects | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>projects/[id]</h1>
    </>
  );
};

export default Projects;
