import type { NextPage } from "next";
import Head from "next/head";
import prisma from "lib/prisma";

const Projects: NextPage = (props: any) => {
  const { project } = props;
  return (
    <>
      <Head>
        <title>Projects | VRMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{project.name}</h1>
    </>
  );
};

export default Projects;

export async function getServerSideProps(context) {
  const id = Number(context.params.id);

  if (!id) {
    return {
      redirect: {
        destination: "/projects",
        permanent: false,
      },
    };
  }

  const project = await prisma.project.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
    },
  });
  return {
    props: { project },
  };
}
